const { Sequelize } = require('sequelize')
require('dotenv').config()
const toBool = (x) => x === 'true'
const DATABASE_URL = process.env.DATABASE_URL || './database.db'
module.exports = {
 SESSION_ID:
  process.env.SESSION_ID ||
  'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUpzMURuZzFlQ0M0aSs4cy9FU09iREN0OG1mQ09IS2lyRWZJRm5yT1psdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK1VRUkU5dFFkQVZ0WXdPc25oZDN3c1JSa1lLOHVWQlJXTGxjeGJneDBoaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRUHFUNWIzZm91VzZTYmpwbXFKbTIxWGduQXg4YzFCckdKcjhiTEwrWWw0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIvTndncjRyYWRzYWNjbDFkNWx1bVBDVUdlUDZTdkZKb2U2WFVOcWZKbVhzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVJUUFoM1NXRFVweHBMdkxMOFNqVjM2UnoxelYySEJZeTY5MkdmYWVGMWs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJGTGczeTQ4bUtoY2tzekNEQzZZUkpJSWFCTUpWM1RidVNQMzNHM3pQMnc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia014R0JaVlJ1YjRBc01hUWN5QXMrQzhzNWlvczBuNVA1RFIraVZ3S1dIYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSWN0RmNLWWdlZjJ2dmRKMGRQTHFJTWtoSk1Qd0lLd0F6aVFKbmhVeEVpcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InBucStwSWo4UWZOSFFjSEdvdHVlNWZ0Z1FMRS9FUUw0TzI4UWFGY0ZPMXZDMFFNNFROcHJBOHZJUUR6YWRlUytkbHpQaXpEK3dJelkvaHowbGJMd2lBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTczLCJhZHZTZWNyZXRLZXkiOiJiTWpoL3RSSHdrZ0pqNHptUDcrOTZtOHpJOGlmVkpGOXRNVGdtSDFlQTI0PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNDgwMzk2MDczNzVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMTZFMjMyMEJGOTk4OTZDRTE1RTkzOEFGRTdCOEQxNzIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyMTYzMjU5Nn0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0ODAzOTYwNzM3NUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI0MkIxQjE5QjM4NThCMURENTkyODg4RjdDQTA3MTkxNCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIxNjMyNTk4fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyMzQ4MDM5NjA3Mzc1QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjlGNTQwRjBBOUE5NUQwREU4MkJGMkUyRDE5ODExRjM4In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MjE2MzI2MzB9LHsia2V5Ijp7InJlbW90ZUppZCI6IjIzNDgwMzk2MDczNzVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNzlCMTExQkNGOUIwQkQ1QjQzQkQwOTJEQ0FBREJDM0QifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyMTYzMjY2Mn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoia29EVzRGM1NTUGFsbEJWdFY1WnRXdyIsInBob25lSWQiOiJhNjU2OTM4My1lMTllLTQ4ZjYtYjI1Yy1mM2E3MGQ4MzIzNjciLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRVZERW0rcmI0WmNxd0QrRnA5S1puUUNRYUMwPSJ9LCJyZWdpc3RlcmVkIjpmYWxzZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJka0kxZiszS1hSNUdaTXVhQStnSFRwVm5FS3M9In0sInJlZ2lzdHJhdGlvbiI6e30sImFjY291bnQiOnsiZGV0YWlscyI6IkNMZkdtcklCRU1lTytMUUdHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ6WmVYOTJrRmU1QWxvZEpYM21DUStjQVE4MFlya3ZOcCtIdDRoNkw5alJNPSIsImFjY291bnRTaWduYXR1cmUiOiJPb1NqWXdUS294Rks4MmpUWnJxMHozY0kwRm05Y1pBNkpnVXZjWDFKRHMycDN6MkNQbksrWlh5NHhmaWIwK3UrMm1xRm9mVXJYUlh4U3ZwUzFNNGtBUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiL3NZRE1rZHFMNE5Ba2VnK0lSdkdtSDJudVJocGxBSDZ4N2t2MnB1L3V5SndRRlpraUJ3REhYWUIxMlozR0FwRTJmTURPc2xFMVpTdmduQ0Jxa0MwaFE9PSJ9LCJtZSI6eyJpZCI6IjIzNDgwMzk2MDczNzU6MzFAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxMzk0NjY2OTgxNTgxMTA6MzFAbGlkIiwibmFtZSI6ImRhbmllbGZ4MDExIn0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDgwMzk2MDczNzU6MzFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYzJYbC9kcEJYdVFKYUhTVjk1Z2tQbkFFUE5HSzVMemFmaDdlSWVpL1kwVCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FrSUFnPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzIxNjMyNTkwLCJsYXN0UHJvcEhhc2giOiIxdjRBNmMiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUtxSyJ9',
 SESSION_FLUSH: process.env.SESSION_FLUSH || 'false',
 OWNER_NAME: process.env.OWNER_NAME || 'EX-BOTS',
 BOT_NAME: process.env.BOT_NAME || 'Zenon-bot',
 SUDO: process.env.SUDO || '2348039607375,2349027862116,2347089816866,2349054039891,2347045035241',
 WORK_TYPE: process.env.WORK_TYPE || 'private',
 TIME_ZONE: process.env.TZ || 'Africa/Lagos',
 HANDLERS: process.env.HANDLER === 'false' || process.env.HANDLER === 'null' ? '^' : '[#]',
 ANTILINK: toBool(process.env.ANTI_LINK) || false,
 LOGS: toBool(process.env.LOGS) || true,
 ANTILINK_ACTION: process.env.ANTI_LINK || 'kick',
 LANG: process.env.LANG || 'EN',
 AUTH_TOKEN: '',
 RMBG_KEY: process.env.RMBG_KEY || false,
 BRANCH: 'main',
 WARN_COUNT: 3,
 PACKNAME: process.env.PACKNAME || 'EX-BOTS',
 WELCOME_MSG: process.env.WELCOME_MSG || 'Hi @user Welcome to @gname',
 GOODBYE_MSG: process.env.GOODBYE_MSG || 'Hi @user It was Nice Seeing you',
 AUTHOR: process.env.AUTHOR || 'EX-BOTS',
 HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || '',
 HEROKU_API_KEY: process.env.HEROKU_API_KEY || '',
 HEROKU: toBool(process.env.HEROKU) || false,
 AUTO_READ: toBool(process.env.AUTO_READ) || false,
 AUTO_STATUS_READ: toBool(process.env.AUTO_STATUS_READ) || false,
 PROCESSNAME: process.env.PROCESSNAME || 'EX-BOTS',
 SESSION_URL: process.env.SESSION_URL || '',
 DELETED_LOG: toBool(process.env.DELETED_LOG) || false,
 DELETED_LOG_CHAT: process.env.DELETED_LOG_CHAT || false,
 REMOVEBG: process.env.REMOVEBG || false,
 DATABASE_URL: DATABASE_URL,
 STATUS_SAVER: toBool(process.env.STATUS_SAVER) || true,
 DATABASE:
  DATABASE_URL === './database.db'
   ? new Sequelize({
      dialect: 'sqlite',
      storage: DATABASE_URL,
      logging: false,
     })
   : new Sequelize(DATABASE_URL, {
      dialect: 'postgres',
      ssl: true,
      protocol: 'postgres',
      dialectOptions: {
       native: true,
       ssl: { require: true, rejectUnauthorized: false },
      },
      logging: false,
     }),
}
